baseurl = "https://fredericgingras.ca/"
languageCode = "en-us"
title = "Hi, I'm Frederic."
pygmentsStyle = "vim"

[Author]
	name = "Frederic Gingras"

[Permalinks]
	posts = "/:year/:month/:slug"

[Params]
	twitter = "https://twitter.com/fredericgingras"
	github = "https://github.com/kiasaki"
	linkedin = "http://www.linkedin.com/in/fgingras"
	disqus = "fredericgingras"
